name: Android Build

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      # gradlew лежит в папке V2rayNG
      - name: Grant execute permission for gradlew
        run: |
          cd V2rayNG
          chmod +x gradlew

      # основной билд (с фиксом CI-проблем)
      - name: Build Debug APK
        run: |
          cd V2rayNG
          ./gradlew assembleDebug \
            -x lint \
            --no-daemon \
            --stacktrace \
            -Dorg.gradle.jvmargs="-Xmx4g -XX:+UseParallelGC"

      # загрузка APK
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: V2rayNG/app/build/outputs/apk/debug/*.apk
